#!/usr/bin/env bash
# Install (or re-install) Discord Webhook Manager for CMK on a Debian/Ubuntu host.
# Idempotent: safe to re-run. Existing .env and database are never overwritten.
#
#   git clone https://github.com/fu-sasa/discord-webhook-manager-cmk.git /opt/dwm
#   sudo /opt/dwm/deploy/install.sh
set -euo pipefail

APP_DIR=/opt/dwm
DATA_DIR=/var/lib/dwm
BACKUP_DIR=/var/backups/dwm
SVC_USER=dwm
SERVICE=discord-webhook-manager
NODE_MAJOR=24
PUBLIC_URL=${PUBLIC_BASE_URL:-https://dwm-pkg-v2.tesatech.net}
BIND_PORT=${PORT:-8080}

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "root で実行してください (sudo $0)"

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# ---- packages ---------------------------------------------------------------
log "パッケージを確認しています"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates gnupg git sqlite3 >/dev/null

if ! command -v node >/dev/null 2>&1 || [ "$(node -p 'process.versions.node.split(".")[0]')" -lt 22 ]; then
  log "Node.js ${NODE_MAJOR}.x を導入しています"
  install -d -m 0755 /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg --yes
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list
  apt-get update -qq
  apt-get install -y -qq nodejs >/dev/null
fi
log "Node.js $(node -v)"

# ---- user and directories ---------------------------------------------------
if ! id -u "$SVC_USER" >/dev/null 2>&1; then
  log "サービスユーザー ${SVC_USER} を作成しています"
  useradd --system --home-dir "$DATA_DIR" --shell /usr/sbin/nologin "$SVC_USER"
fi

install -d -o "$SVC_USER" -g "$SVC_USER" -m 0750 "$DATA_DIR" "$BACKUP_DIR"

# ---- application files ------------------------------------------------------
if [ "$REPO_DIR" != "$APP_DIR" ]; then
  log "アプリケーションを ${APP_DIR} へ配置しています"
  install -d -m 0755 "$APP_DIR"
  tar -C "$REPO_DIR" --exclude=.git --exclude=node_modules --exclude=dist --exclude=data -cf - . \
    | tar -C "$APP_DIR" -xf -
fi

cd "$APP_DIR"
log "依存関係をインストールしています"
npm ci --no-audit --no-fund
log "ビルドしています"
npm run build
log "開発用依存を削除しています"
npm prune --omit=dev --no-audit --no-fund

# ---- configuration ----------------------------------------------------------
GENERATED_PASSWORD=""
if [ ! -f "$APP_DIR/.env" ]; then
  log ".env を生成しています"
  GENERATED_PASSWORD=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)
  cat > "$APP_DIR/.env" <<EOF
# Generated by deploy/install.sh on $(date -Is)
# APP_SECRET を変更すると保存済み Webhook URL が復号できなくなります。
APP_SECRET=$(openssl rand -hex 32)
ADMIN_PASSWORD=$GENERATED_PASSWORD
HOST=127.0.0.1
PORT=$BIND_PORT
PUBLIC_BASE_URL=$PUBLIC_URL
DATABASE_PATH=$DATA_DIR/dwm.db
TZ_DISPLAY=Asia/Tokyo
SCHEDULER_TICK_MS=5000
SCHEDULER_BATCH=10
MISFIRE_GRACE_SECONDS=86400
MAX_ATTEMPTS=5
SESSION_TTL_SECONDS=604800
COOKIE_SECURE=1
LOG_LEVEL=info
EOF
else
  log ".env は既に存在するため変更しません"
fi

# Code stays root-owned so the service account cannot rewrite its own binary.
chown -R root:root "$APP_DIR"
chown "$SVC_USER:$SVC_USER" "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"
chmod +x "$APP_DIR/deploy/"*.sh

# ---- systemd ----------------------------------------------------------------
log "systemd ユニットを設定しています"
install -m 0644 "$APP_DIR/deploy/${SERVICE}.service" /etc/systemd/system/
install -m 0644 "$APP_DIR/deploy/dwm-backup.service" /etc/systemd/system/
install -m 0644 "$APP_DIR/deploy/dwm-backup.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now "$SERVICE"
systemctl enable --now dwm-backup.timer

sleep 3
if ! systemctl is-active --quiet "$SERVICE"; then
  systemctl status "$SERVICE" --no-pager -l || true
  die "サービスの起動に失敗しました。上のログを確認してください。"
fi

HEALTH=$(curl -fsS "http://127.0.0.1:${BIND_PORT}/healthz" || echo 'FAILED')
log "ヘルスチェック: $HEALTH"

echo
echo "────────────────────────────────────────────────────────────────────"
echo " インストールが完了しました"
echo "────────────────────────────────────────────────────────────────────"
echo " 待ち受け : http://127.0.0.1:${BIND_PORT}"
echo " 公開 URL : ${PUBLIC_URL}"
if [ -n "$GENERATED_PASSWORD" ]; then
  echo
  echo " 管理パスワード（この一度きりの表示です。今すぐ控えてください）:"
  echo "     $GENERATED_PASSWORD"
  echo
  echo " ログイン後、設定画面から任意のパスワードに変更してください。"
fi
echo
echo " 残りの手動作業: Cloudflare Zero Trust ダッシュボードで、このホストの"
echo " 既存トンネルに Public Hostname を追加してください。"
echo "     Subdomain/Domain : $(echo "$PUBLIC_URL" | sed 's|https\?://||')"
echo "     Service          : HTTP  →  localhost:${BIND_PORT}"
echo "────────────────────────────────────────────────────────────────────"
